version: "3.9"
services:
  db:
    image: postgres:alpine
    volumes:
      - data:/var/lib/postgresql/data:delegated
      - ./initdb:/docker-entrypoint-initdb.d:cached
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-dev}
      - POSTGRES_USER=${POSTGRES_USER:-dev_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dev_password}
  cache:
    image: redis:alpine
    command: ["redis-server","--appendonly","yes"]
    volumes:
      - redis-data:/data:delegated
  app:
    build:
      context: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: rails7-full
    volumes:
      - .:/app:cached
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://dev_user:dev_password@db}
      - RAILS_ENV=${RAILS_ENV:-development}
      - REDIS_URL=${REDIS_URL:-redis://cache:6397/0/${RAILS_ENV:-development}}
    ports:
      - "3000:3000"
    depends_on:
      - db
      - cache
volumes:
  data:
  redis-data: