default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: dev/development

test:
  <<: *default
  database: dev/test

production:
  <<: *default
  database: dev/production